package com.github.sebing.luminar;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;

/**
 *
 * @author m_816259
 */
public class WindowsToMacCatalogConverter extends javax.swing.JFrame {

    /**
     * Creates new form WindowsTomacCatalogCoverter
     */
    public WindowsToMacCatalogConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        winFileTextField = new javax.swing.JTextField();
        winBrowseButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        macFileTextField = new javax.swing.JTextField();
        macBrowseButton = new javax.swing.JButton();
        migrateButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Windows to Mac Luminar Catalog Converter");

        panel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Windows catalog file");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panel.add(jLabel1, gridBagConstraints);

        winFileTextField.setPreferredSize(new java.awt.Dimension(200, 26));
        panel.add(winFileTextField, new java.awt.GridBagConstraints());

        winBrowseButton.setLabel("Browse");
        winBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winBrowseButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        panel.add(winBrowseButton, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Mac catalog file");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel.add(macFileTextField, gridBagConstraints);

        macBrowseButton.setLabel("Browse");
        macBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                macBrowseButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        panel.add(macBrowseButton, gridBagConstraints);

        migrateButton.setText("Migrate");
        migrateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                migrateButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        panel.add(migrateButton, gridBagConstraints);

        jLabel3.setText("<html><p>Copyright © 2020 sebing<br /><br />Donations:<br />Bitcoin - 13zdfsZpSwYMB3TsWQr6djDkDjXJgwwaUV<br /> Paypal - sebingeo@yahoo.com</p><br /> <p>Compliments, suggestions and issues mail: sebingeo@yahoo.com</p></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        panel.add(jLabel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void winBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winBrowseButtonActionPerformed
            String absolutePath = filePath();
                winFileTextField.setText(absolutePath);
                System.out.println(absolutePath);        // TODO add your handling code here:
    }//GEN-LAST:event_winBrowseButtonActionPerformed

    private void macBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_macBrowseButtonActionPerformed
         String absolutePath = filePath();
                macFileTextField.setText(absolutePath);
                System.out.println(absolutePath);
    }//GEN-LAST:event_macBrowseButtonActionPerformed

    private void migrateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_migrateButtonActionPerformed
        int result = JOptionPane.showConfirmDialog(panel,
                        "Do you back up your catalog files?",
                        "Are you sure?",
                        JOptionPane.YES_NO_OPTION);

                if(result == JOptionPane.YES_OPTION){
                    new Migrate(winFileTextField.getText(),macFileTextField.getText());
                    JOptionPane.showMessageDialog(panel,"Re-import the catalog file to Luminar");
                }
    }//GEN-LAST:event_migrateButtonActionPerformed

     private String filePath() {
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showOpenDialog(panel);
        return jFileChooser.getSelectedFile().getAbsolutePath();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowsToMacCatalogConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowsToMacCatalogConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowsToMacCatalogConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowsToMacCatalogConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                new WindowsToMacCatalogConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton macBrowseButton;
    private javax.swing.JTextField macFileTextField;
    private javax.swing.JButton migrateButton;
    private javax.swing.JPanel panel;
    private javax.swing.JButton winBrowseButton;
    private javax.swing.JTextField winFileTextField;
    // End of variables declaration//GEN-END:variables
}
